/* GENERATED by media-audit.py — probed, never guessed. Do not hand-edit.
 * playable:true means a HEAD request for that URL returned 200.
 */
window.IFM_MEDIA =
{
"IFM-R01": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-R01.mp4",
"dur": "0:08",
"silent": false
},
"IFM-R02": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-R02.mp4",
"dur": "0:08",
"silent": false
},
"IFM-R03": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-R03.mp4",
"dur": "0:08",
"silent": false
},
"IFM-R04": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-R04.mp4",
"dur": "0:08",
"silent": false
},
"IFM-R05": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-R05.mp4",
"dur": "0:08",
"silent": false
},
"IFM-R06": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-R06.mp4",
"dur": "0:08",
"silent": false
},
"IFM-R07": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-R07.mp4",
"dur": "0:08",
"silent": false
},
"IFM-R08": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-R08.mp4",
"dur": "0:08",
"silent": false
},
"IFM-R09": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-R09.mp4",
"dur": "0:08",
"silent": false
},
"IFM-R10": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-R10.mp4",
"dur": "0:08",
"silent": false
},
"IFM-R11": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-R11.mp4",
"dur": "0:08",
"silent": false
},
"IFM-001": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-002": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-003": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-004": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-004.mp4",
"dur": "0:08",
"silent": true
},
"IFM-005": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-006": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-006.mp4",
"dur": "0:08",
"silent": true
},
"IFM-007": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-007.mp4",
"dur": "0:08",
"silent": true
},
"IFM-008": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-008.mp4",
"dur": "0:08",
"silent": true
},
"IFM-009": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-009.mp4",
"dur": "0:08",
"silent": true
},
"IFM-010": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-010.mp4",
"dur": "0:08",
"silent": true
},
"IFM-011": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-011.mp4",
"dur": "0:08",
"silent": true
},
"IFM-012": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-012.mp4",
"dur": "0:08",
"silent": true
},
"IFM-013": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-013.mp4",
"dur": "0:08",
"silent": true
},
"IFM-014": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-014.mp4",
"dur": "0:08",
"silent": true
},
"IFM-015": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-015.mp4",
"dur": "0:08",
"silent": true
},
"IFM-016": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-017": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-018": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-019": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-020": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-021": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-022": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-023": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-024": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-025": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-026": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-027": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-028": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-029": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-030": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-031": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-032": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-033": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-034": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-035": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-036": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/teasers/swayamvar-teaser.mp4",
"dur": "0:15",
"silent": false
},
"IFM-040": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-040.mp4",
"dur": "0:05",
"silent": false
},
"IFM-041": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-041.mp4",
"dur": "0:05",
"silent": false
},
"IFM-042": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-042.mp4",
"dur": "0:05",
"silent": false
},
"IFM-043": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-043.mp4",
"dur": "0:08",
"silent": false
},
"IFM-050": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-050.mp4",
"dur": "0:05",
"silent": true
},
"IFM-052": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-054": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-055": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-056": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-057": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-057.mp4",
"dur": "0:08",
"silent": false
},
"IFM-058": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-058.mp4",
"dur": "0:08",
"silent": false
},
"IFM-059": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-059.mp4",
"dur": "0:08",
"silent": false
},
"IFM-060": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-060.mp4",
"dur": "0:08",
"silent": false
},
"IFM-061": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-062": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-063": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-064": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-065": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-066": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-067": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-068": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-069": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-070": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-071": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-072": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-073": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-074": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-075": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-076": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-076.mp4",
"dur": "0:06",
"silent": false
},
"IFM-077": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-077.mp4",
"dur": "0:08",
"silent": false
},
"IFM-078": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-078.mp4",
"dur": "0:08",
"silent": false
},
"IFM-079": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-080": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-081": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-082": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-083": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-084": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-085": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-086": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-087": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-088": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-088.mp4",
"dur": "0:08",
"silent": false
},
"IFM-089": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-090": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-091": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-092": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-093": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-093.mp4",
"dur": "0:08",
"silent": false
},
"IFM-094": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-095": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-096": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-097": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-098": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-098.mp4",
"dur": "0:08",
"silent": false
},
"IFM-099": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-100": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-101": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-101.mp4",
"dur": "0:08",
"silent": false
},
"IFM-102": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-103": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-104": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-105": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-106": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-107": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-108": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-109": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-110": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-111": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-112": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-113": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-114": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-114.mp4",
"dur": "0:08",
"silent": false
},
"IFM-115": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-116": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-117": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-118": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-119": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-120": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-121": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-122": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-123": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-124": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-125": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-126": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-127": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-128": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-129": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-130": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-131": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-132": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-133": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-133.mp4",
"dur": "0:08",
"silent": true
},
"IFM-134": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-135": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-136": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-137": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-138": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-139": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-140": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-141": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-141.mp4",
"dur": "0:08",
"silent": false
},
"IFM-142": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-142.mp4",
"dur": "0:08",
"silent": false
},
"IFM-143": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-144": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-145": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-145.mp4",
"dur": "0:08",
"silent": false
},
"IFM-146": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-146.mp4",
"dur": "0:08",
"silent": false
},
"IFM-147": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-148": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-149": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-150": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-151": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-151.mp4",
"dur": "0:08",
"silent": false
},
"IFM-152": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-153": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-153.mp4",
"dur": "0:08",
"silent": false
},
"IFM-154": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-154.mp4",
"dur": "0:08",
"silent": false
},
"IFM-155": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-155.mp4",
"dur": "0:08",
"silent": false
},
"IFM-156": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-157": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-158": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-159": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-160": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-160.mp4",
"dur": "0:08",
"silent": false
},
"IFM-161": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-161.mp4",
"dur": "0:08",
"silent": false
},
"IFM-162": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-162.mp4",
"dur": "0:12",
"silent": false
},
"IFM-163": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-164": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-165": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-166": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-167": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-168": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-169": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-169.mp4",
"dur": "0:08",
"silent": false
},
"IFM-170": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-171": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-172": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-172.mp4",
"dur": "0:07",
"silent": false
},
"IFM-173": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-174": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-175": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-176": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-177": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-178": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-179": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-180": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-180.mp4",
"dur": "0:08",
"silent": false
},
"IFM-181": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-181.mp4",
"dur": "0:08",
"silent": false
},
"IFM-182": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-183": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-184": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-185": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-186": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-186.mp4",
"dur": "0:03",
"silent": true
},
"IFM-187": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-188": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-189": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-190": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-191": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-192": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-193": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-194": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-195": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-196": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-197": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-198": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-199": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-200": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-201": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-202": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-203": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-204": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-205": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-206": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-207": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-208": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-209": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-210": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-211": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-212": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-213": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-214": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-215": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-216": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-217": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-251": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-252": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-253": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-254": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-255": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-256": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-257": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-258": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-259": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-260": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-261": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-262": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-263": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-264": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-265": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-266": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-267": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-268": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-269": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-270": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-271": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-272": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-273": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-274": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-275": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-276": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-277": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-278": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-279": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-279.mp4",
"dur": "0:08",
"silent": false
},
"IFM-280": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-280.mp4",
"dur": "0:08",
"silent": false
},
"IFM-281": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-281.mp4",
"dur": "0:08",
"silent": false
},
"IFM-282": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-282.mp4",
"dur": "0:06",
"silent": false
},
"IFM-283": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-283.mp4",
"dur": "0:07",
"silent": false
},
"IFM-284": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-284.mp4",
"dur": "0:08",
"silent": false
},
"IFM-285": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-285.mp4",
"dur": "0:04",
"silent": false
},
"IFM-286": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-286.mp4",
"dur": "0:08",
"silent": false
},
"IFM-287": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-287.mp4",
"dur": "0:08",
"silent": false
},
"IFM-288": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-289": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-290": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-291": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-292": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-293": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-294": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-295": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-296": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-297": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-298": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-299": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-300": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-301": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-302": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-303": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-304": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-305": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-306": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-307": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-308": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/teasers/kbc-teaser.mp4",
"dur": "0:12",
"silent": false
},
"IFM-309": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/teasers/ltm-teaser.mp4",
"dur": "0:12",
"silent": false
},
"IFM-310": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/teasers/stockrush-teaser.mp4",
"dur": "0:12",
"silent": false
},
"IFM-311": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-315": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-316": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-317": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-318": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-319": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-320": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-321": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-322": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-323": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-324": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-325": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-326": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-327": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-328": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-329": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-330": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-331": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-332": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-333": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-334": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-335": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-336": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-337": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-338": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-339": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-340": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-341": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-342": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-343": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-344": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-345": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-346": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-346.mp4",
"dur": "0:05",
"silent": false
},
"IFM-347": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-347.mp4",
"dur": "0:04",
"silent": false
},
"IFM-348": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-348.mp4",
"dur": "0:07",
"silent": false
},
"IFM-349": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-349.mp4",
"dur": "0:06",
"silent": false
},
"IFM-350": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-350.mp4",
"dur": "0:02",
"silent": false
},
"IFM-351": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-351.mp4",
"dur": "0:06",
"silent": false
},
"IFM-352": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-352.mp4",
"dur": "0:08",
"silent": false
},
"IFM-353": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-353.mp4",
"dur": "0:06",
"silent": false
},
"IFM-354": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-354.mp4",
"dur": "0:08",
"silent": false
},
"IFM-355": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-355.mp4",
"dur": "0:08",
"silent": false
},
"IFM-356": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-356.mp4",
"dur": "0:06",
"silent": false
},
"IFM-357": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-357.mp4",
"dur": "0:08",
"silent": false
},
"IFM-358": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-358.mp4",
"dur": "0:05",
"silent": false
},
"IFM-359": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-360": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-360.mp4",
"dur": "0:03",
"silent": false
},
"IFM-361": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-361.mp4",
"dur": "0:03",
"silent": false
},
"IFM-362": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-363": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-364": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-365": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-366": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-367": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-367.mp4",
"dur": "0:08",
"silent": false
},
"IFM-368": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-368.mp4",
"dur": "0:04",
"silent": false
},
"IFM-369": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-369.mp4",
"dur": "0:06",
"silent": false
},
"IFM-370": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-371": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-372": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-373": {
"kind": "carousel",
"playable": false,
"url": null
},
"IFM-374": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-375": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-376": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-376.mp4",
"dur": "0:08",
"silent": false
},
"IFM-377": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-377.mp4",
"dur": "0:08",
"silent": false
},
"IFM-378": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-378.mp4",
"dur": "0:04",
"silent": false
},
"IFM-379": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-379.mp4",
"dur": "0:00",
"silent": false
},
"IFM-380": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-380.mp4",
"dur": "0:08",
"silent": false
},
"IFM-381": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-381.mp4",
"dur": "0:08",
"silent": false
},
"IFM-382": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-382.mp4",
"dur": "0:08",
"silent": false
},
"IFM-383": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-383.mp4",
"dur": "0:07",
"silent": false
},
"IFM-384": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-385": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-386": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-386.mp4",
"dur": "0:08",
"silent": false
},
"IFM-387": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-388": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-388.mp4",
"dur": "0:08",
"silent": false
},
"IFM-389": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-389.mp4",
"dur": "0:07",
"silent": false
},
"IFM-390": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-390.mp4",
"dur": "0:08",
"silent": false
},
"IFM-391": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-392": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-393": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-394": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-395": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-396": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-397": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-397.mp4",
"dur": "0:08",
"silent": false
},
"IFM-398": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-398.mp4",
"dur": "0:08",
"silent": false
},
"IFM-399": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-399.mp4",
"dur": "0:08",
"silent": false
},
"IFM-400": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-400.mp4",
"dur": "0:08",
"silent": false
},
"IFM-401": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-401.mp4",
"dur": "0:08",
"silent": false
},
"IFM-402": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-402.mp4",
"dur": "0:06",
"silent": false
},
"IFM-403": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-403.mp4",
"dur": "0:08",
"silent": false
},
"IFM-404": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-404.mp4",
"dur": "0:08",
"silent": false
},
"IFM-405": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-405.mp4",
"dur": "0:03",
"silent": false
},
"IFM-406": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-406.mp4",
"dur": "0:08",
"silent": false
},
"IFM-407": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-407.mp4",
"dur": "0:08",
"silent": false
},
"IFM-408": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-408.mp4",
"dur": "0:08",
"silent": false
},
"IFM-409": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-409.mp4",
"dur": "0:04",
"silent": false
},
"IFM-410": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-410.mp4",
"dur": "0:11",
"silent": false
},
"IFM-411": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-411.mp4",
"dur": "0:08",
"silent": false
},
"IFM-412": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-412.mp4",
"dur": "0:08",
"silent": false
},
"IFM-413": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-414": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-415": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-415.mp4",
"dur": "0:07",
"silent": false
},
"IFM-416": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-416.mp4",
"dur": "0:03",
"silent": false
},
"IFM-417": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-417.mp4",
"dur": "0:05",
"silent": false
},
"IFM-418": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-418.mp4",
"dur": "0:08",
"silent": false
},
"IFM-419": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-419.mp4",
"dur": "0:02",
"silent": false
},
"IFM-420": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-420.mp4",
"dur": "0:03",
"silent": false
},
"IFM-421": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-421.mp4",
"dur": "0:08",
"silent": false
},
"IFM-422": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-422.mp4",
"dur": "0:08",
"silent": false
},
"IFM-423": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-423.mp4",
"dur": "0:03",
"silent": false
},
"IFM-424": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-424.mp4",
"dur": "0:06",
"silent": false
},
"IFM-425": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-425.mp4",
"dur": "0:03",
"silent": false
},
"IFM-426": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-426.mp4",
"dur": "0:08",
"silent": false
},
"IFM-427": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-427.mp4",
"dur": "0:03",
"silent": false
},
"IFM-428": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-428.mp4",
"dur": "0:08",
"silent": false
},
"IFM-429": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-429.mp4",
"dur": "0:06",
"silent": false
},
"IFM-430": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-430.mp4",
"dur": "0:05",
"silent": false
},
"IFM-431": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-431.mp4",
"dur": "0:08",
"silent": false
},
"IFM-432": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-432.mp4",
"dur": "0:08",
"silent": false
},
"IFM-433": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-433.mp4",
"dur": "0:03",
"silent": false
},
"IFM-434": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-434.mp4",
"dur": "0:08",
"silent": false
},
"IFM-435": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-435.mp4",
"dur": "0:02",
"silent": false
},
"IFM-436": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-436.mp4",
"dur": "0:08",
"silent": false
},
"IFM-437": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-437.mp4",
"dur": "0:07",
"silent": false
},
"IFM-438": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-438.mp4",
"dur": "0:07",
"silent": false
},
"IFM-439": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-440": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-441": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-441.mp4",
"dur": "0:08",
"silent": false
},
"IFM-442": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-442.mp4",
"dur": "0:08",
"silent": false
},
"IFM-443": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-443.mp4",
"dur": "0:08",
"silent": false
},
"IFM-444": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-444.mp4",
"dur": "0:04",
"silent": false
},
"IFM-445": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-445.mp4",
"dur": "0:12",
"silent": false
},
"IFM-446": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-446.mp4",
"dur": "0:08",
"silent": false
},
"IFM-447": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-447.mp4",
"dur": "0:08",
"silent": false
},
"IFM-448": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-448.mp4",
"dur": "0:08",
"silent": false
},
"IFM-449": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-449.mp4",
"dur": "0:08",
"silent": false
},
"IFM-450": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-450.mp4",
"dur": "0:04",
"silent": false
},
"IFM-451": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-452": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-452.mp4",
"dur": "0:08",
"silent": false
},
"IFM-453": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-453.mp4",
"dur": "0:08",
"silent": false
},
"IFM-454": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-454.mp4",
"dur": "0:08",
"silent": false
},
"IFM-455": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-455.mp4",
"dur": "0:08",
"silent": false
},
"IFM-456": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-456.mp4",
"dur": "0:08",
"silent": false
},
"IFM-457": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-457.mp4",
"dur": "0:08",
"silent": false
},
"IFM-458": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-458.mp4",
"dur": "0:12",
"silent": false
},
"IFM-459": {
"kind": "video",
"playable": false,
"url": null,
"dur": null,
"silent": false
},
"IFM-460": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-460.mp4",
"dur": "0:03",
"silent": false
},
"IFM-461": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-461.mp4",
"dur": "0:08",
"silent": false
},
"IFM-462": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-462.mp4",
"dur": "0:08",
"silent": false
},
"IFM-463": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-463.mp4",
"dur": "0:08",
"silent": false
},
"IFM-464": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-464.mp4",
"dur": "0:08",
"silent": false
},
"IFM-465": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-465.mp4",
"dur": "0:08",
"silent": false
},
"IFM-466": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-466.mp4",
"dur": "0:08",
"silent": false
},
"IFM-467": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-467.mp4",
"dur": "0:08",
"silent": false
},
"IFM-468": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-468.mp4",
"dur": "0:08",
"silent": false
},
"IFM-469": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-469.mp4",
"dur": "0:08",
"silent": false
},
"IFM-470": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-470.mp4",
"dur": "0:08",
"silent": false
},
"IFM-471": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-471.mp4",
"dur": "0:08",
"silent": false
},
"IFM-472": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-472.mp4",
"dur": "0:12",
"silent": false
},
"IFM-473": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-473.mp4",
"dur": "0:08",
"silent": false
},
"IFM-474": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-474.mp4",
"dur": "0:08",
"silent": false
},
"IFM-475": {
"kind": "video",
"playable": true,
"url": "https://ifm-deploy.vercel.app/content/clips/IFM-475.mp4",
"dur": "0:05",
"silent": false
},
"IFM-476": {
"kind": "image",
"playable": false,
"url": null
},
"IFM-477": {
"kind": "image",
"playable": false,
"url": null
}
};
