#!/usr/bin/env /usr/bin/python3
"""Determine, by probing, which assets have a genuinely playable video.

  /usr/bin/python3 media-audit.py            # probe and write media-map.js
  /usr/bin/python3 media-audit.py --offline  # rebuild from the last probe, no network

WHY THIS EXISTS
  The UI was showing a play control whenever `type == 'Video'`. That is not evidence of
  anything. Of 179 video-type assets, only 33 actually have a file that loads:

    clips        30 playable
    teasers       3 playable, 1 missing
    reels         0 playable  — content/reels/ is not whitelisted in .vercelignore,
                                so none of the 11 reels ever reached production
    wealth-conv   0 playable  — 10 URLs return 404
    other         0 playable  — 13 URLs return 404
    (and 102 video-type assets carry no media URL at all)

  So 146 of 179 "videos" offered a play button that could not deliver. This script is the
  only thing standing between that and the interface, and it decides by asking the server,
  never by reading a metadata field.

  The output is a SEPARATE file. The approved catalogue, taxonomy and search engine are
  frozen and are not touched.
"""
import json, os, re, sys, urllib.request, urllib.error

HERE = os.path.dirname(os.path.abspath(__file__))
CAT = os.path.join(HERE, 'v1-catalogue.js')
OUT = os.path.join(HERE, 'media-map.js')
CACHE = os.path.join(HERE, '.media-probe.json')
MEDIA = re.compile(r'\.(mp4|mov|m4v|webm)(\?|$)', re.I)


def load_catalogue():
    s = open(CAT, encoding='utf-8').read()
    return json.loads(s[s.index('['):s.rindex(']') + 1])


def candidate_url(r):
    """The only URLs worth probing: ones that actually name a media file.

    A Drive *viewer* link (drive.google.com/file/d/.../view) is a web page, not a video —
    it can never be played inline, so it is deliberately not a candidate.
    """
    for f in ('video', 'drive'):
        u = (r.get(f) or '').strip()
        if u.startswith('http') and MEDIA.search(u):
            return u
    return None


def probe(url, timeout=20):
    req = urllib.request.Request(url, method='HEAD',
                                 headers={'User-Agent': 'ifm-media-audit/1.0'})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status
    except urllib.error.HTTPError as e:
        return e.code
    except Exception:
        return 0


def main():
    rows = load_catalogue()
    offline = '--offline' in sys.argv
    cache = {}
    if os.path.exists(CACHE):
        cache = json.load(open(CACHE))

    urls = {}
    for r in rows:
        u = candidate_url(r)
        if u:
            urls.setdefault(u, []).append(r['id'])

    if not offline:
        for i, u in enumerate(sorted(urls), 1):
            cache[u] = probe(u)
            print('  [%3d/%d] %s %s' % (i, len(urls), cache[u], u[-58:]), file=sys.stderr)
        json.dump(cache, open(CACHE, 'w'), indent=0)

    out, stats = {}, {'playable': 0, 'unavailable': 0, 'image': 0, 'carousel': 0}
    for r in rows:
        if r.get('library') is False:
            continue
        t = r.get('type') or ''
        u = candidate_url(r)
        ok = bool(u) and cache.get(u) == 200
        if t == 'Video':
            # `silent` only means something for a file that actually plays.
            out[r['id']] = {'kind': 'video', 'playable': ok,
                            'url': u if ok else None,
                            'silent': bool(r.get('silent')) if ok else False}
            stats['playable' if ok else 'unavailable'] += 1
        elif t == 'Carousel':
            out[r['id']] = {'kind': 'carousel', 'playable': False, 'url': None}
            stats['carousel'] += 1
        else:
            out[r['id']] = {'kind': 'image', 'playable': False, 'url': None}
            stats['image'] += 1

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('/* GENERATED by media-audit.py — probed, never guessed. Do not hand-edit.\n'
                ' * playable:true means a HEAD request for that URL returned 200.\n */\n'
                'window.IFM_MEDIA =\n')
        json.dump(out, f, indent=0)
        f.write(';\n')
    print(json.dumps(stats, indent=1))
    print('wrote', OUT)


if __name__ == '__main__':
    main()
