/* The 20-asset acceptance set — tagged against the V1 taxonomy, 16 Sep 2026.
 *
 * HOW THESE WERE TAGGED (this is the pipeline being tested, run by hand once):
 *   evidence = existing title + description + keywords + session + folder/source context,
 *   plus VISUAL analysis of the thumbnail or a pulled video frame where the row's own text
 *   was not enough.
 *
 * Two rules were applied strictly:
 *   1. `source` is NEVER inferred from the event. A workshop photo does not tell you who
 *      shot it. Where nothing establishes it, source is 'Unknown'.
 *   2. `person: Hiral` is only claimed where she was actually identified, not assumed from
 *      "a presenter". For the 6 Apr office session that meant pulling a 1200px frame and
 *      comparing against the known founder reference before claiming it.
 *
 * `search_terms` is the field that makes natural language work. It carries synonyms, the
 * specific finance terms that deliberately have no Topic of their own (SIP, XIRR, SGB),
 * and affect words ("candid", "warm") that a person would actually type. It is NOT
 * taxonomy and is never rendered as a tag.
 *
 * `slide_text` is what was read off a projector/screen in frame. On IFM-099 this produced
 * five topics the row's own description never mentioned — see PROTOTYPE-FINDINGS.md.
 */
window.IFM_TAGGED20 = [
{
  id:'IFM-101', title:'Clip — Explaining Gold Investments (SGB & Gold Funds)',
  type:'Video', format:'Hiral Speaking',
  topic:['Gold','Asset Allocation','Mutual Funds','ETFs'],
  person:['Hiral','Student'], source:'Unknown', session:'', status:'Raw',
  thumb:'../thumbs/IFM-101.jpg', video:'https://ifm-deploy.vercel.app/content/clips/IFM-101.mp4',
  drive:'https://drive.google.com/file/d/1NdM9y701az7VViop_skRPvLosg2NFD50/view',
  date:'2026-04-06',
  description:"Hiral presents the 'Gold: Your Portfolio's Safe Haven' slide, walking through the ways to invest in gold while two women listen from the boardroom table.",
  slide_text:"Gold: Your Portfolio's Safe Haven. Ways to invest in gold: SGBs (best way to invest in gold, for low risk long term investors, backed by RBI); Gold Mutual Funds (invest into ETFs, gold mining and gold-related assets); ETFs (highly liquid, traded on the stock exchange); Digital Gold; Physical Gold (low liquidity, high risk of theft, making and storage costs). 5-10% of portfolio.",
  search_terms:'sgb sovereign gold bond gold funds gold etf digital gold physical gold safe haven hedge portfolio allocation five to ten percent rbi ways to invest in gold jewellery bullion talking explaining teaching speaking',
  _evidence:'Visual: 1200px frame pulled from the source photo of the same session; slide read directly. Person confirmed against the founder reference photo. Source not established by any file/folder evidence -> Unknown.',
},
{
  id:'IFM-099', title:'Gold as a Safe Haven Talk',
  type:'Image', format:'Hiral Speaking',
  topic:['Gold','Asset Allocation','Mutual Funds','ETFs'],
  person:['Hiral','Student'], source:'Unknown', session:'', status:'Raw',
  thumb:'../thumbs/IFM-099.jpg',
  drive:'https://drive.google.com/file/d/1qYxKCBvl_bfa7Bh1_KZ-wShkF1kJhmPD/view',
  date:'2026-04-06',
  description:'Hiral points at the gold allocation pie chart on screen while two attendees watch from the foreground. White shirt, red trousers, office boardroom.',
  slide_text:"Gold: Your Portfolio's Safe Haven. Ways to invest in gold: SGBs, Gold Mutual Funds, ETFs, Digital Gold, Physical Gold. 5-10% of portfolio.",
  search_terms:'gold safe haven pie chart allocation sgb sovereign gold bond gold funds etf portfolio hedge slide presenting pointing',
  _evidence:'Same session as IFM-101. Slide text read off a 1200px Drive thumbnail.',
},
{
  id:'IFM-216', title:'July: Ever Wondered — central banks and gold',
  type:'Video', format:'Hiral Speaking',
  topic:['Gold','Markets & Economy'],
  person:['Hiral'], source:'Aakara', session:'Aakara July delivery', status:'Ready',
  thumb:'../thumbs/IFM-216.jpg',
  drive:'https://drive.google.com/drive/folders/1Q38Vzk2Cj4BAnL9HQs3WFwLFUeD4OI',
  date:'2026-07-28',
  description:"Reel: Hiral against a gold-bar backdrop asking 'Ever wondered why central banks own so much gold?'",
  slide_text:'',
  search_terms:'central bank reserves gold bars bullion rbi hook ever wondered reel gold reserves talking speaking',
  _evidence:'Source Aakara established by the delivery folder it came from.',
},
{
  id:'IFM-088', title:'Clip — Open Q&A on the Questions Slide',
  type:'Video', format:'Student Question',
  topic:['Investing','Money Conversations'],
  person:['Hiral','Student'], source:'Unknown', session:'', status:'Raw',
  thumb:'../thumbs/IFM-088.jpg', video:'https://ifm-deploy.vercel.app/content/clips/IFM-088.mp4',
  drive:'https://drive.google.com/file/d/1YLM4M6hJA3D0oJl_RxtH-ufC9gvEAuCl/view',
  date:'2026-04-06',
  description:"Hiral stands beside a colourful 'QUESTIONS?' slide fielding queries from women seated around the boardroom table — the interactive Q&A wrap-up of a workshop.",
  slide_text:'QUESTIONS?',
  search_terms:'q and a qna question answer asking doubts queries audience participation interactive wrap up discussion hands up curious',
  _evidence:'Same 6 Apr office session; person confirmed by session match.',
},
{
  id:'IFM-286', title:'Teens workshop — Hiral teaching compounding',
  type:'Video', format:'Hiral Speaking',
  topic:['Compounding','Investing','Wealth'],
  person:['Hiral','Student'], source:'Sakshi', session:'Teens — Aug 2026', status:'Raw',
  thumb:'../thumbs/IFM-286.jpg',
  drive:'https://drive.google.com/file/d/1AiqrV7-IuvBDrYsODMUsQBLLga5AsGqY/view',
  date:'2026-08-18',
  description:"Hiral presents the 'What if you invest every month' compounding slide — 20/25/30/40-year wealth outcomes — to the teens.",
  slide_text:'What if you invest every month. 20 years / 25 years / 30 years / 40 years wealth outcomes.',
  search_terms:'compounding compound interest monthly investing sip systematic investment plan start early time in market long term teens youth teenagers wealth growth cagr',
  _evidence:"Source Sakshi established by the row's own keywords naming her as the uploader, not inferred from the event.",
},
{
  id:'IFM-317', title:'Corporate workshop — Hiral teaching the room',
  type:'Image', format:'Hiral Speaking',
  topic:['Investing','Women & Money'],
  person:['Hiral','Student'], source:'Unknown', session:'Corporate — 4 Jul 2026', status:'Raw',
  thumb:'../thumbs/IFM-317.jpg',
  drive:'https://drive.google.com/file/d/1p2yqh9WvAG05z2CpAAUlqiEhLsX1pqhp/view',
  date:'2026-07-04',
  description:'Hiral at the head of the boardroom table mid-explanation, hand out, addressing a full row of women. Shot from behind the attendees so the room reads as packed. Wide 4:3 with crop room.',
  slide_text:'',
  search_terms:'corporate workshop boardroom packed room teaching explaining presenting audience women professional office wide crop hero',
  _evidence:'Corporate shoot folder gives no producer. Source Unknown.',
},
{
  id:'IFM-319', title:'Corporate workshop — DSLR portraits of Hiral',
  type:'Image', format:'Portrait',
  topic:[], person:['Hiral'], source:'Unknown', session:'Corporate — 4 Jul 2026', status:'Raw',
  thumb:'../thumbs/IFM-319.jpg',
  drive:'https://drive.google.com/drive/folders/1iZye0DSRAsi8WgQIYApMNhx45GcVNs',
  date:'2026-07-04',
  description:'Canon-shot portraits: Hiral seated at the boardroom table behind an open MacBook, red sleeveless top, warm wood background. 11 JPEGs plus matching CR3 RAW files. The cleanest founder headshots IFM has.',
  slide_text:'',
  search_terms:'portrait headshot founder dslr canon raw cr3 professional press media kit agency bio photo profile picture author photo',
  _evidence:'A /camera subfolder with CR3 RAWs implies a camera operator but names nobody. Source Unknown rather than a guess at External.',
},
{
  id:'IFM-067', title:'Hiral standing portrait, arms crossed — wood backdrop',
  type:'Image', format:'Portrait',
  topic:[], person:['Hiral'], source:'IFM / In-house', session:'', status:'Raw',
  thumb:'../thumbs/IFM-067.jpg',
  drive:'https://drive.google.com/file/d/1mA21c5_IPGHcyf_cOVPxkrXsUVcGORSi/view',
  date:'2026-03-24',
  description:'Three-quarter standing portrait of Hiral, arms crossed against a warm wood-panel wall, gentle closed-mouth smile. White eyelet-sleeve shirt, pale blue striped skirt.',
  slide_text:'',
  search_terms:'portrait standing arms crossed founder profile photo about page bio professional confident wood backdrop headshot',
  _evidence:'Source In-house carried over from the existing row.',
},
{
  id:'IFM-268', title:'September: Reviews (workshop testimonials)',
  type:'Carousel', format:'Testimonial',
  topic:[], person:['No Person'], source:'Aakara', session:'Aakara September delivery', status:'Ready',
  thumb:'../thumbs/IFM-268.jpg',
  drive:'https://drive.google.com/drive/folders/1Cx0NIOhg_pNzos0UdMpW_KKAYrMTA-',
  date:'2026-09-01',
  description:"Five-artboard testimonial carousel. Cream cover with an oversized dark-green 'review' wordmark bleeding off all edges and a white card reading \"Here's what people are saying about our workshops\". Artboards 2-5 carry participant quote cards.",
  slide_text:"review. Here's what people are saying about our workshops.",
  search_terms:'testimonial testimonials review reviews feedback social proof word of mouth participant quotes what people say happy customers praise recommendation',
  _evidence:'Aakara September delivery folder.',
},
{
  id:'IFM-362', title:'Flagship graduate with her certificate',
  type:'Image', format:'Certificate',
  topic:[], person:['Student'], source:'Unknown',
  session:'Investing for Mummies Flagship graduation — Aug 2026', status:'Raw',
  thumb:'../thumbs/IFM-362.jpg',
  drive:'https://drive.google.com/file/d/1l1SCV70bis0224e7Ynrya9oMeuKOZejd/view',
  date:'2026-09-04',
  description:"A grey-haired woman in a lilac striped shirt beams at the camera holding up her IFM 'Certificate of Completion' for the Flagship course, dated August 2026. Seated at the boardroom table with an open notebook.",
  slide_text:'Certificate of Completion — Investing for Mummies Flagship, August 2026.',
  search_terms:'certificate completion graduate graduation proud smiling happy achievement social proof alumni finished course flagship mums',
  _evidence:'Consent note on the source row: certificate names visible.',
},
{
  id:'IFM-288', title:'Teens workshop — certificates group photo',
  type:'Image', format:'Certificate',
  topic:[], person:['Hiral','Student'], source:'Sakshi', session:'Teens — Aug 2026', status:'Raw',
  thumb:'../thumbs/IFM-288.jpg',
  drive:'https://drive.google.com/file/d/1auLjBxrzWjPJSzfyL-AmrJkVWksa7fl2/view',
  date:'2026-08-17',
  description:'Certificate ceremony — eight teens holding their Certificates of Completion with Hiral, big smiles in the boardroom.',
  slide_text:'Certificate of Completion.',
  search_terms:'certificate ceremony teens teenagers youth group smiling celebration achievement graduation happy proud minors',
  _evidence:"Source Sakshi from the row's keywords. NOTE: consent = minors visible.",
},
{
  id:'IFM-291', title:'Teens workshop — room wide shot',
  type:'Image', format:'B-roll',
  topic:[], person:['Hiral','Student'], source:'Sakshi', session:'Teens — Aug 2026', status:'Raw',
  thumb:'../thumbs/IFM-291.jpg',
  drive:'https://drive.google.com/file/d/14b3CEUYhQyAXfUG65qN6sRBhGfEH2o_B/view',
  date:'2026-08-17',
  description:'Wide view of the boardroom mid-session — Hiral at the head of the table, screen live, teens with worksheets.',
  slide_text:'',
  search_terms:'wide shot room establishing setup venue context b-roll cutaway supporting footage boardroom session in progress teens',
  _evidence:'Classified B-roll rather than Classroom Moment: it is an establishing/context frame, not a human moment. See findings — this boundary is the fuzziest in the taxonomy.',
},
{
  id:'IFM-339', title:'RSS workshop — audience applauding',
  type:'Image', format:'Classroom Moment',
  topic:['Women & Money'], person:['Student'], source:'Aakara',
  session:'RSS workshop (Balsabha) — 4 Jun 2026', status:'Ready',
  thumb:'../thumbs/IFM-339.jpg',
  drive:'https://drive.google.com/file/d/10yIA3Kf-EBt3wiKdzk9BhzFRz8ADbQiU/view',
  date:'2026-06-04',
  description:'Candid from the back of the room: around a dozen women in office chairs applauding, several smiling toward the front. Shot past the seated rows rather than posed.',
  slide_text:'',
  search_terms:'candid applause clapping applauding smiling laughing warm joyful fun funny lively engaged happy audience reaction natural unposed real moment energy',
  _evidence:'Aakara source from the delivery folder.',
},
{
  id:'IFM-179', title:'Types of Insurance slide',
  type:'Image', format:'Hiral Speaking',
  topic:['Insurance','Financial Planning'],
  person:['Hiral','Student'], source:'Unknown', session:'', status:'Raw',
  thumb:'../thumbs/IFM-179.jpg',
  drive:'https://drive.google.com/file/d/193E3rVDPJyZbX35xq2NLLzcgeBnk91Vt/view',
  date:'2026-04-06',
  description:"Hiral stands beside the wall screen showing a pink-headed 'Types of Insurance' slide while attentive women look on from around the table.",
  slide_text:'Types of Insurance.',
  search_terms:'insurance term life health cover policy premium protection risk types of insurance explaining teaching slide',
  _evidence:'Same 6 Apr office session as IFM-088/099/101.',
},
{
  id:'IFM-009', title:'Wealth Conversation Ch.4 — Magic of Compounding',
  type:'Video', format:'B-roll',
  topic:['Compounding','Investing','Wealth'],
  person:['No Person'], source:'AI Generated', session:'Wealth Conversation series', status:'Ready',
  thumb:'../thumbs/IFM-009.jpg',
  drive:'https://ifm-deploy.vercel.app/wealth-conversation-videos/chapter4-magic-of-compounding.mp4',
  date:'2026-06-11',
  description:"Cash bundles rain down beside a calendar and a sign reading '₹10,000 invested at 12% per year', stacking into a tower labelled '20 yrs ₹96,463' that morphs into a skyscraper.",
  slide_text:'₹10,000 invested at 12% per year. 20 yrs ₹96,463.',
  search_terms:'compounding compound interest growth money tower skyscraper twelve percent returns cagr xirr long term twenty years ai generated animation b-roll cutaway supporting footage',
  _evidence:"Source AI Generated — the legacy type was 'AI Video', which V1 treats as a Source, not a Type.",
},
{
  id:'IFM-007', title:'Wealth Conversation Ch.2 — Inflation',
  type:'Video', format:'B-roll',
  topic:['Inflation & Interest Rates','Money Mindset'],
  person:['No Person'], source:'AI Generated', session:'Wealth Conversation series', status:'Raw',
  thumb:'../thumbs/IFM-007.jpg',
  drive:'https://ifm-deploy.vercel.app/wealth-conversation-videos/chapter2-inflation.mp4',
  date:'2026-06-11',
  description:'A single coin sprouts a green seedling that grows into a gold-coin tree. Test render — the final Ch.2 hero is still pending.',
  slide_text:'',
  search_terms:'inflation rising prices purchasing power money plant coin tree seedling growth rbi repo rate interest rates cost of living ai generated animation b-roll',
  _evidence:"Legacy status was 'In Production', which V1 folds to Raw.",
},
{
  id:'IFM-R01', title:'Money Map — game reel',
  type:'Video', format:'Social / Promotional',
  topic:['Managing Money','Saving','Financial Planning'],
  person:['Other Person'], source:'IFM / In-house', session:'Game reels — Jun 2026', status:'Ready',
  thumb:'../thumbs/IFM-R01.jpg', video:'https://ifm-deploy.vercel.app/content/reels/moneymap-15s.mp4',
  drive:'https://ifm-deploy.vercel.app/content/reels/moneymap-15s.mp4',
  date:'2026-06-20',
  description:"15s vertical promo reel. Opens on AI-animated budgeting-workshop footage with the hook 'Where does your money actually go?', cuts to the purple Money Map budget tracker, closes on the IFM end-card.",
  slide_text:"Where does your money actually go? Every rupee, mapped.",
  search_terms:'money map budget tracker budgeting game promo reel vertical gen z spending where money goes expense tracking app promo',
  _evidence:'Hybrid: AI-generated footage assembled in-house. Source recorded as the producer (IFM), not the footage. See findings — hybrids are an open question.',
},
{
  id:'IFM-R05', title:'Stock Rush — game reel',
  type:'Video', format:'Social / Promotional',
  topic:['Stock Market','Stocks / Equity','Investing'],
  person:['Student'], source:'IFM / In-house', session:'Game reels — Jun 2026', status:'Ready',
  thumb:'../thumbs/IFM-R05.jpg', video:'https://ifm-deploy.vercel.app/content/reels/stockrush-15s.mp4',
  drive:'https://ifm-deploy.vercel.app/content/reels/stockrush-15s.mp4',
  date:'2026-06-20',
  description:'15s vertical reel mixing teacher and student views — students watching a live leaderboard, the host leaderboard screen, then a player trading screen. Black/green market theme.',
  slide_text:'Teacher view. Student view.',
  search_terms:'stock rush stock market game trading leaderboard classroom teacher student promo reel equity shares nifty sensex simulation gameplay',
  _evidence:'',
},
{
  id:'IFM-018', title:'Power of Compounding',
  type:'Carousel', format:'Social Graphic',
  topic:['Compounding','Investing','Wealth'],
  person:['No Person'], source:'Aakara', session:'Aakara June delivery', status:'Ready',
  thumb:'../thumbs/IFM-018.jpg',
  drive:'https://drive.google.com/drive/folders/1a17dQ-OiJ479dcYTNbyLQm7JYPWSCp',
  date:'2026-06-11',
  description:"Mint-green cover slide: 'Wanna end up RICHER than someone investing WAAAAAYYYYY more money than you?' above a photo of a hand clutching crumpled rupee notes.",
  slide_text:'Wanna end up RICHER than someone investing WAAAAAYYYYY more money than you?',
  search_terms:'compounding compound interest start early time in market richer sip systematic investment plan carousel hook mint green rupee notes',
  _evidence:'',
},
{
  id:'IFM-020', title:'Savings vs Investing',
  type:'Carousel', format:'Social Graphic',
  topic:['Saving vs Investing','Saving','Investing'],
  person:['No Person'], source:'Aakara', session:'Aakara June delivery', status:'Ready',
  thumb:'../thumbs/IFM-020.jpg',
  drive:'https://drive.google.com/drive/folders/1uMZq13u1Hf_nvMX6WMqPcAs2fjII7m',
  date:'2026-06-11',
  description:"Textured beige cover titled 'What is Savings Vs Investments' with a hand dropping a banknote into a pink piggy bank.",
  slide_text:'What is Savings Vs Investments.',
  search_terms:'savings vs investing saving investment difference piggy bank basics beginner explainer fd fixed deposit bank account emergency fund',
  _evidence:'',
},
];
