/**
 * level/loader.js — builds a level from JSON, and validates loudly.
 *
 * ARCHITECTURE.md level format:
 *   { id, name, chapter, sky, par, ammo:['sip'], blocks:[{mat,x,y,w,h,rot}],
 *     villains:[{type,x,y}], props:[{type,x,y}] }
 *
 * "The loader validates and throws loudly on bad data." A level with a typo'd material or a
 * block half-buried in the ground must fail at load with a message naming the index, not
 * silently produce a structure that behaves oddly six shots later.
 *
 * ── SEEDED IMPERFECTION ──────────────────────────────────────────────────────
 * Every block gets a jitter of a few thousandths of a unit on x and rotation, drawn from
 * rng.js. It is far too small to see (0.004 world units is a twentieth of a pixel at our
 * camera distance) and far too small to destabilise a stack, but it makes the level a real
 * function of the seed, which is what keeps `SS.seed(n)` honest. Hand-authored levels with
 * zero randomness would make the determinism gate's "different seed => different world"
 * check trivially, uselessly true.
 */

import * as THREE from 'three';
import { Block } from './blocks.js';
import { structure } from './structure.js';
import { Entity, makeBody, shapes } from './entity.js';
import { mat, PALETTE, MATERIAL_NAMES } from '../art/materials.js';
import { inkAll, RAMP_SOFT, RAMP_STD } from '../art/toon.js';
/**
 * THE BACKDROP LIVES IN art/environment.js. It used to be ~120 lines at the bottom of this
 * file; it is now the sky, four haze veils, two mountain ranges carrying the IFM peak, the
 * sky roundel, drifting mist, three hill bands, two tree bands, three cloud layers and two
 * instanced grass bands, which is not level-loading and does not belong here.
 * `updateEnvironment` is re-exported below so main.js's import is unchanged.
 */
import { buildEnvironment, updateEnvironment, settingGround } from '../art/environment.js';
import { world } from '../world.js';
import { rngRange, rngJitter } from '../rng.js';
import { setStarTable, LEVEL_ORDER } from '../progression.js';

/**
 * THE VILLAIN REGISTRY IS A MERGE — one entry per archetype file. Every `villains/<x>.js`
 * exports its own `VILLAIN_TYPES` and this is the only place they are joined, so adding a
 * villain costs one import and one spread, and `validate()` below can still name every type
 * it knows when a level asks for one it does not.
 */
import { VILLAIN_TYPES as V_LOTTERY_UNCLE } from '../villains/lotteryUncle.js';
import { VILLAIN_TYPES as V_CREDIT_CARD_TRAP } from '../villains/creditCardTrap.js';
import { VILLAIN_TYPES as V_PONZI_PYRAMID } from '../villains/ponziPyramid.js';
import { VILLAIN_TYPES as V_CONMAN } from '../villains/conmanSprite.js';
const VILLAIN_TYPES = { ...V_LOTTERY_UNCLE, ...V_CREDIT_CARD_TRAP, ...V_PONZI_PYRAMID,
                        ...V_CONMAN };

export { updateEnvironment };

const BREAKABLE = new Set(['wood', 'glass', 'stone', 'prop']);

export const LEVELS = { l1: null, l2: null, l3: null };   // filled by loadLevelData

/**
 * HARNESS FIXTURES LIVE SOMEWHERE ELSE, AND THE `_` PREFIX IS THE ROUTE.
 *
 * `levels/` held 15 `_`-prefixed probe levels (`_p3-stone`, `_pw-drop`, `_l3v-recruit`, …)
 * next to the three real ones. They are not content and must not ship — but they are also
 * not dead: 14 of the 15 are loaded by standing gates (`pw-gate`, `p3-mats`, `p3-r6-late`,
 * the `p6-*` and `crit-P3-*` families), so deleting them would delete the instruments.
 * They live in `levels/_probe/` now — one directory to exclude at publish time — and every
 * scenario still asks for them by the same bare id.
 */
const fixtureDir = (id) => (String(id).startsWith('_') ? '_probe/' : '');

/**
 * THE MEASURED STAR THRESHOLDS — `levels/stars.json`, regenerated by
 * `_tools/scenarios/p13-sweep.mjs`. See src/progression.js for why they are data and not a
 * formula. Fetched once, alongside the first level. A failure here is a WARNING, not a throw:
 * an ungraded level is still playable (a win is worth 1 star, never 0), an unbootable game is
 * not — and HOOKS.md forbids gating `ready` on a fetch that can hang.
 */
let starTableFetched = false;
async function ensureStarTable() {
  if (starTableFetched) return;
  starTableFetched = true;
  try {
    const res = await fetch(new URL('../../levels/stars.json', import.meta.url), { cache: 'no-store' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    setStarTable(await res.json());
  } catch (e) {
    console.warn(`[level] could not load levels/stars.json (${e.message}) — every level will be ` +
                 `UNGRADED (a win still scores 1 star, never 0). Regenerate it with ` +
                 `_tools/scenarios/p13-sweep.mjs (APPLY=1).`);
    setStarTable(null);
  }
}

/** Fetch + parse + validate. Throws with a useful message. */
export async function loadLevelData(id) {
  await ensureStarTable();
  // Memoised: SS.seed() rebuilds the level on every call, and HOOKS.md forbids gating on a
  // fetch that can hang. One fetch per level id per page load, then it is pure memory.
  if (LEVELS[id]) return LEVELS[id];
  const rel = `levels/${fixtureDir(id)}${id}.json`;
  const url = new URL(`../../${rel}`, import.meta.url);
  let json;
  try {
    const res = await fetch(url, { cache: 'no-store' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    json = await res.json();
  } catch (e) {
    throw new Error(`[level] could not load ${rel} — ${e.message}`);
  }
  validate(json, id);
  LEVELS[id] = json;
  return json;
}

function validate(L, id) {
  const die = (msg) => { throw new Error(`[level ${id}] ${msg}`); };
  if (!L || typeof L !== 'object') die('not an object');
  for (const k of ['id', 'name', 'ammo', 'blocks', 'villains']) {
    if (!(k in L)) die(`missing required key "${k}"`);
  }
  if (!Array.isArray(L.ammo) || !L.ammo.length) die('"ammo" must be a non-empty array');
  if (!Array.isArray(L.blocks)) die('"blocks" must be an array');
  if (!Array.isArray(L.villains) || !L.villains.length) die('"villains" must be a non-empty array');

  L.blocks.forEach((b, i) => {
    if (!BREAKABLE.has(b.mat)) {
      die(`blocks[${i}].mat = "${b.mat}" is not one of ${[...BREAKABLE].join('|')}`);
    }
    for (const k of ['x', 'y', 'w', 'h']) {
      if (!Number.isFinite(b[k])) die(`blocks[${i}].${k} is not a finite number (got ${b[k]})`);
    }
    if (b.w <= 0 || b.h <= 0) die(`blocks[${i}] has a non-positive size ${b.w}x${b.h}`);
    // A block sunk into the ground will jump out on the first step and knock the tower over
    // "for no reason". Catch it here instead.
    if (b.y - b.h / 2 < -0.02) die(`blocks[${i}] starts below ground (y=${b.y}, h=${b.h})`);
  });

  /**
   * `teaches` is the one-line scam payload. The level-complete overlay prints it verbatim —
   * it IS the educational deliverable, so a shipped level without one is a content bug, not a
   * cosmetic one. Fixtures are exempt: they teach nothing and are never shown to a player.
   */
  if (LEVEL_ORDER.includes(id) && (typeof L.teaches !== 'string' || L.teaches.trim().length < 8)) {
    die('missing a usable "teaches" line — the level-complete overlay has nothing to teach with');
  }

  /**
   * THE UNWINNABLE-LEVEL GUARD. `debt: true` blocks cannot break until something with
   * `role: "interest"` is destroyed, so a level that ships the shield without the weak point
   * is not "hard", it is impossible — and it would fail as a level that looks completely
   * normal until a student has spent all five shots on it. Caught here, at load, in the same
   * spirit as the "teaches" check above: a content bug, not a cosmetic one.
   */
  const shielded = L.blocks.filter(b => b.debt === true).length;
  const meters = L.blocks.filter(b => b.role === 'interest').length;
  if (shielded > 0 && meters === 0) {
    die(`${shielded} block(s) are shielded with "debt":true but nothing carries `
      + `"role":"interest" — the shield can never be cleared and the level cannot be won`);
  }
  if (meters > 1) die(`${meters} blocks carry "role":"interest"; exactly one is the weak point`);

  /**
   * THE CRUSHED-VILLAIN GUARD — a HEADROOM test, not an overlap test.
   *
   * Every villain in this game rests slightly sunk into the platform it stands on (about
   * 0.30 of a unit, resting contact plus authoring slack), so "overlaps a block" flags all of
   * them and is useless. What actually kills one is being sandwiched: a block close above AND
   * a block close below, with less clear height between them than the villain occupies.
   *
   * l1 shipped like that for days. Its bay's side posts shrank from 1.2 to 0.50 when the
   * level's heights were rescaled, nobody re-checked the bay, and one of its two villains was
   * crushed to death on the first physics step — at tick 0 the level already read 1 villain
   * and 6,100 points. The level was then a one-shot clear, which presented to the player as
   * "the cannon is far too strong" rather than as the authoring bug it was.
   */
  const VR = 0.54, VH = VR * 2;
  L.villains.forEach((v, i) => {
    /**
     * EMBEDDED, not merely resting. A villain rests slightly sunk into its platform by design,
     * but its CENTRE inside a block is always a mistake — it is spawned in the solid, and the
     * solver ejects it. This is a different failure from the pinned-between-two case below and
     * the headroom test cannot see it: l8 shipped a villain buried in a cantilevered beam and
     * opened with 5 of 6 villains and 5,000 free points.
     */
    for (const b of L.blocks) {
      if (Math.abs(b.x - v.x) < b.w / 2 - 0.02 && Math.abs(b.y - v.y) < b.h / 2 - 0.02) {
        die(`villains[${i}] (${v.type} at ${v.x},${v.y}) is spawned with its centre INSIDE a `
          + `${b.mat} block at ${b.x},${b.y} (${b.w}x${b.h}). It will be ejected on the first step.`);
      }
    }
    let floor = -Infinity, ceil = Infinity;
    for (const b of L.blocks) {
      if (Math.abs(b.x - v.x) >= b.w / 2 + VR * 0.5) continue;   // not in this column
      const top = b.y + b.h / 2, bot = b.y - b.h / 2;
      if (top <= v.y + VR * 0.5) floor = Math.max(floor, top);
      if (bot >= v.y - VR * 0.5) ceil = Math.min(ceil, bot);
    }
    if (floor > -Infinity && ceil < Infinity) {
      const gap = ceil - floor;
      if (gap < VH - 0.10) {
        die(`villains[${i}] (${v.type} at ${v.x},${v.y}) has only ${gap.toFixed(2)} units of `
          + `headroom between the block below (top ${floor.toFixed(2)}) and the block above `
          + `(bottom ${ceil.toFixed(2)}). It needs ${VH.toFixed(2)} and will be crushed on the `
          + `first physics step.`);
      }
    }
  });

  L.villains.forEach((v, i) => {
    if (!VILLAIN_TYPES[v.type]) {
      die(`villains[${i}].type = "${v.type}" is unknown. Known: ${Object.keys(VILLAIN_TYPES).join(', ')}`);
    }
    if (!Number.isFinite(v.x) || !Number.isFinite(v.y)) die(`villains[${i}] has a bad position`);
  });
  return L;
}

// ---------------------------------------------------------------------------
// BUILD
// ---------------------------------------------------------------------------

/** @returns {{blocks:number, villains:number}} */
export function buildLevel(L) {
  world.level = L;
  buildGround();
  const env = buildEnvironment(world.scene);
  world.environment = env;
  new Entity({ mesh: env, body: null, collider: null, material: null, tag: 'decor' });

  for (const b of L.blocks) {
    new Block({
      matName: b.mat,
      x: b.x + rngJitter(0.004),
      y: b.y,
      w: b.w, h: b.h,
      rot: (b.rot ?? 0) + rngJitter(0.0025),
      debt: b.debt === true,
      role: b.role ?? null,
    });
  }

  for (const v of L.villains) {
    const Type = VILLAIN_TYPES[v.type];
    new Type({ x: v.x + rngJitter(0.004), y: v.y });
  }

  world.ammoQueue = L.ammo.slice();
  world.ammoUsed = 0;

  /**
   * The joint graph is solved from the authored poses, AFTER every block exists. It is what
   * turns "this block broke" into "the tower comes down" — see level/structure.js.
   */
  structure.build();

  return { blocks: L.blocks.length, villains: L.villains.length };
}

/**
 * ── STREAM BALLAST: REMOVED 2026-09-11, AS ITS OWN NOTE INSTRUCTED ──────────────────────
 *
 * `consumeLegacyEnvironmentStream()` stood here. It replayed ~2018 draws that the backdrop
 * used to take from the SIMULATION rng stream before it moved into art/environment.js, so
 * that the block jitter (`rngJitter(0.004)` below) stayed bit-identical to the jitter
 * levels/stars.json's recorded proof plans had been measured under. Its docblock said, in
 * as many words: delete this the day stars.json is next re-derived.
 *
 * That day is today — the l1/l2/l3 rescale moved the score distribution so far that all
 * nine recorded plans failed the star gate outright, so every proof in stars.json has been
 * re-measured against this build rather than bridged back to the old one. Keeping the
 * ballast would have pinned the new proofs to a stream shape that nothing in the game
 * produces any more.
 *
 * The finding it leaves behind is worth more than the function was: a jitter of four
 * THOUSANDTHS of a world unit was the difference between l3's recorded 3-star clear and not
 * winning at all. Recorded plans are knife-edge by nature, so a proof that only wins under
 * one exact stream is a coincidence with a filename. The re-derivation therefore records
 * each proof's margin across more than one seed — see levels/stars.json.
 */

function buildGround() {
  const H = 3.0;
  const D = 9.0;                    // shallower than it looks — see the note below
  /**
   * The ground takes the SETTING's cover when it has one. `mat()` with overrides returns a
   * fresh material instead of the shared cached one — one per level build, the same trade the
   * interest meter makes in level/blocks.js, and the only way a per-level tint is possible at
   * all while other levels keep the cached material.
   */
  const gt = settingGround();
  const m = gt ? mat('ground', { color: gt[0], emissive: gt[1] }) : mat('ground');
  const { body, collider } = makeBody({
    kind: 'fixed', x: 10, y: -H / 2, m,
    shape: shapes.box(120, H, D),
    contactForce: 40,
  });

  /**
   * The ground's FRONT FACE is a big piece of screen real estate in a side-on game — it is
   * the bottom 15% of every frame, forever. A single flat brown box there is the fastest
   * way to make the whole thing look unfinished. So it is built as a designed cross-section:
   * a grass cap with an overhanging lip, three soil strata that get darker with depth, and
   * embedded pebbles. Keeping D small (9 rather than 14) also stops the near face from
   * looming: at a 30 mm-equivalent FOV the front face is much closer than the play plane.
   */
  const g = new THREE.Group();

  const strata = [
    { c: 0x8a5730, h: 0.70, y: 1.00 },      // just under the roots
    { c: 0x77482a, h: 0.95, y: 0.18 },
    { c: 0x603721, h: 1.35, y: -0.98 },     // deep, cool, nearly out of frame
    // BEDROCK. Absurdly deep on purpose: on a tall portrait phone the camera has to sit far
    // enough back that the frame extends ~14 world units below the grass, and without this
    // you look straight under the level and see the sky-coloured backdrop through the floor.
    { c: 0x452617, h: 30.0, y: -16.0 },
  ];
  for (const st of strata) {
    const b = new THREE.Mesh(new THREE.BoxGeometry(120, st.h, D + 0.02),
      new THREE.MeshToonMaterial({ color: st.c, map: stoneGrainMap(), gradientMap: RAMP_SOFT() }));
    b.position.y = st.y;
    b.receiveShadow = true;
    b.userData.noInk = true;
    g.add(b);
  }

  // pebbles pressed into the cut face
  const pebbleMat = new THREE.MeshToonMaterial({ color: 0x9a8570, gradientMap: RAMP_SOFT() });
  for (let i = 0; i < 44; i++) {
    const pb = new THREE.Mesh(new THREE.SphereGeometry(rngRange(0.06, 0.17), 7, 5), pebbleMat);
    pb.position.set(rngRange(-46, 56), rngRange(-1.4, 1.5), D / 2 - 0.03);
    pb.scale.set(1, rngRange(0.6, 1.0), 0.55);
    pb.userData.noInk = true;
    g.add(pb);
  }

  // grass cap, and the lip that overhangs the cut
  const cap = new THREE.Mesh(new THREE.BoxGeometry(120, 0.52, D + 0.04), m.three);
  cap.position.y = H / 2 - 0.26;
  cap.receiveShadow = true;
  g.add(cap);

  const lip = new THREE.Mesh(new THREE.BoxGeometry(120, 0.30, 0.34),
    mat('ground', { color: 0x6fb83f }).three);
  lip.position.set(0, H / 2 - 0.62, D / 2 + 0.14);
  lip.userData.noInk = true;
  g.add(lip);

  g.position.set(10, -H / 2, 0);
  world.scene.add(g);
  new Entity({ mesh: g, body, collider, material: m, tag: 'ground' });
}

/** Shared, pre-repeated stone grain for the soil strata. */
let _soilTex = null;
function stoneGrainMap() {
  if (!_soilTex) {
    _soilTex = mat('soil').three.map;
    if (_soilTex) { _soilTex.repeat.set(14, 1.4); _soilTex.needsUpdate = true; }
  }
  return _soilTex;
}
