/**
 * progression.js — THE GAME AROUND THE LEVELS: the chain l1 -> l2 -> l3, the star grading,
 * and the saved record. No rendering, no DOM, no physics. Pure state + arithmetic, so both
 * main.js and ui/hud.js can ask it questions without reaching into each other.
 *
 * ── WHY THE STAR THRESHOLDS ARE NOT IN THIS FILE ─────────────────────────────
 * They used to be a formula: `base = 26000 + par*4000`, then 0.7 / 1.15 / 1.55 of it. Every
 * other piece in the game moves the score distribution (P2 the power curve, P3 the damage
 * model, PW the collapse energy, P12 the layouts), and the formula did not move with them.
 * Measured consequences, all recorded in ORCHESTRATOR-NOTES:
 *   · l1 WON, one shot, both villains, 43 200 pts -> 1 star of 3
 *   · l1 WON, three shots, both villains, 21 600 pts -> ZERO stars. A student who just
 *     succeeded was told they had failed.
 *   · l2: 3 stars mathematically unreachable — best measured clear 33 500 against a 58 900
 *     requirement at par 3.
 * So the thresholds are now DATA, measured from the real shot space and regenerated by
 * `_tools/scenarios/p13-sweep.mjs` into `levels/stars.json`. `setStarTable()` below is how
 * that data reaches this module. Nothing here invents a number.
 *
 * ── TWO INVARIANTS THIS FILE OWNS ────────────────────────────────────────────
 * 1. A WON LEVEL CAN NEVER SCORE ZERO STARS. Structural, not a tuned threshold: `grade()`
 *    clamps a win to >= 1. If the clamp ever has to fire it means the table has drifted
 *    below the real distribution, so it also warns and bumps `starsClamped` — which is what
 *    `p13-stargate.mjs` asserts on. A silent clamp would hide exactly the drift that caused
 *    this bug in the first place.
 * 2. 3 STARS MUST BE REACHABLE. That cannot be enforced here (it is a fact about the level,
 *    not about the grader), so it is enforced by the gate: the sweep records the plan that
 *    scored highest and the gate re-plays it and demands 3 stars.
 *
 * ── STORAGE ──────────────────────────────────────────────────────────────────
 * EVERY access is wrapped. `localStorage` can throw on the PROPERTY READ itself (Safari with
 * site data blocked, a thumbnailer, a sandboxed iframe), not just on get/set — so even
 * `'localStorage' in window` is not safe enough and the accessor is behind a try/catch too.
 * A storage failure must never stop the game rendering, so the module keeps an in-memory
 * mirror and carries on: the session still tracks stars, it just will not survive a reload.
 */

/**
 * ── THE CHAIN IS ORDERED BY MEASURED DIFFICULTY, NOT BY WHEN A LEVEL WAS BUILT ──────────────
 *
 * These ids are deliberately NOT in numeric order. The order below is the ranking produced by
 * `_tools/scenarios/diff1.mjs`, which plays eight different six-shot plans against every level
 * and records what fraction of them actually clear it:
 *
 *      l5 .88   l8 .75   l4 .25   l7 .12   l6 .12   l2 .12   l1 .12   l9 .00   l3 .00
 *
 * Re-measured after l4, l7, l8 and l9 were rebuilt with new silhouettes. Four levels
 * changed shape and the ORDER did not move at all — which is the useful kind of null
 * result: the ranking is a property of the levels, not an artefact of one measurement.
 * Ties are broken by how many villains a losing run still downs, then by shots-to-win
 * (l2 and l1 sit level on both rates; l2 wins in 2 shots against l1's 6).
 *
 * The finding that forced this: the three ORIGINAL levels — l1, l2, l3 — measured as the three
 * hardest in the game, and l3 could not be cleared by any plan at all. A player opening the
 * game was being handed its hardest content first and its easiest content at level 5.
 *
 * ONE WARNING ABOUT RE-DERIVING THIS. The first pass of that measurement swept angles 0.24-0.44
 * only and reported l1, l2 and l3 as flatly unwinnable, 0/8 each — while the star sweep, which
 * spans 0.12-0.80, had already found l2 winnable 12 times in 46. The levels were fine; the aim
 * band was too narrow to contain their winning lines. A difficulty number is only as honest as
 * the range of shots it tried, so widen the band before you believe a zero.
 *
 * Level ids never change, so saved progress survives a reshuffle; only the position does.
 */
export const LEVEL_ORDER = ['l5', 'l8', 'l4', 'l7', 'l6', 'l2', 'l1', 'l9', 'l3'];
export const STORE_KEY = 'scam-slingshot.progress.v1';

/** Stars per level x levels = the total on offer. Used by the finish panel. */
export const MAX_STARS = LEVEL_ORDER.length * 3;

// ---------------------------------------------------------------------------
// THE CHAIN
// ---------------------------------------------------------------------------

/** 0-based position in the chain, or -1 for anything that is not a shipped level. */
export function levelIndex(id) { return LEVEL_ORDER.indexOf(id); }

/** 1-based number for the HUD. `null` for a harness fixture, so the HUD can say so. */
export function levelNumber(id) {
  const i = levelIndex(id);
  return i < 0 ? null : i + 1;
}

/** The next level id, or `null` if this is the last one (or not in the chain at all). */
export function nextLevel(id) {
  const i = levelIndex(id);
  return i < 0 || i >= LEVEL_ORDER.length - 1 ? null : LEVEL_ORDER[i + 1];
}

export function isLastLevel(id) { return levelIndex(id) === LEVEL_ORDER.length - 1; }

/** A probe/fixture level — `_`-prefixed ids are harness-only and never part of the chain. */
export function isFixture(id) { return typeof id === 'string' && id.startsWith('_'); }

// ---------------------------------------------------------------------------
// STAR TABLE (data, from levels/stars.json)
// ---------------------------------------------------------------------------

let STAR_TABLE = null;
let warnedMissing = new Set();

/** Diagnostic counter. Non-zero means the table has drifted under the real distribution. */
export const scoring = { starsClamped: 0, table: () => STAR_TABLE };

/**
 * Install the measured threshold table. Called once by level/loader.js after it fetches
 * `levels/stars.json`. Tolerant by design — a malformed entry is skipped and named, because
 * a grading table that half-loads must not take the game down with it.
 */
export function setStarTable(json) {
  const levels = json?.levels;
  if (!levels || typeof levels !== 'object') {
    console.warn('[progression] levels/stars.json has no "levels" object — levels will be UNGRADED ' +
                 '(a win still scores 1 star). Re-derive with _tools/scenarios/p13-sweep.mjs.');
    STAR_TABLE = {};
    return STAR_TABLE;
  }
  const t = {};
  for (const [id, e] of Object.entries(levels)) {
    const { t1, t2, t3 } = e ?? {};
    if (![t1, t2, t3].every(Number.isFinite) || !(t1 < t2 && t2 < t3)) {
      console.warn(`[progression] stars.json entry "${id}" is not three increasing finite ` +
                   `thresholds (got ${t1}, ${t2}, ${t3}) — skipped.`);
      continue;
    }
    // The three PROOF plans (best / cheapest-2-star / weakest win) are carried through
    // untouched: the gate replays them, so they are data this module only forwards.
    t[id] = { t1, t2, t3, proof3: e.proof3 ?? null, proof2: e.proof2 ?? null,
              proofWeak: e.proofWeak ?? null };
  }
  STAR_TABLE = t;
  warnedMissing = new Set();
  return STAR_TABLE;
}

export function thresholdsFor(id) { return STAR_TABLE?.[id] ?? null; }

/**
 * THE GRADER. `won` is an argument rather than inferred from the score, because "did the
 * player clear the level" and "how well did they do it" are two different questions and
 * conflating them is how a won level ended up worth zero stars.
 *
 * @param {string} id     level id
 * @param {number} score  final score including the unused-ammo bonus
 * @param {boolean} won   did every villain go down
 * @returns {number} 0..3
 */
export function grade(id, score, won) {
  if (!won) return 0;
  const t = thresholdsFor(id);
  if (!t) {
    if (!warnedMissing.has(id)) {
      warnedMissing.add(id);
      console.warn(`[progression] no star thresholds for "${id}" in levels/stars.json — ` +
                   `grading it as 1 star (a win is never worth zero). Re-derive with p13-sweep.mjs.`);
    }
    return 1;
  }
  if (score >= t.t3) return 3;
  if (score >= t.t2) return 2;
  if (score >= t.t1) return 1;
  // INVARIANT 1. Loud, counted, and never zero.
  scoring.starsClamped++;
  console.warn(`[progression] "${id}" was WON with ${score} points, below its own 1-star ` +
               `threshold ${t.t1} — awarding 1 star anyway. The table has drifted under the ` +
               `real score distribution: re-derive it (_tools/scenarios/p13-sweep.mjs, APPLY=1).`);
  return 1;
}

// ---------------------------------------------------------------------------
// THE SAVED RECORD
// ---------------------------------------------------------------------------

const blank = () => ({ v: 1, best: {}, hintDone: false, finished: false });
let mem = blank();
let loaded = false;
/** Did the last storage attempt work? The reset UI tells the truth about this. */
export const storage = { available: null, reason: '' };

/** Even the PROPERTY READ can throw. This is the only place localStorage is touched. */
function ls() {
  try {
    const s = globalThis.localStorage;
    // A getter that returns null/undefined is as unusable as one that throws.
    return s && typeof s.getItem === 'function' ? s : null;
  } catch (e) {
    storage.available = false;
    storage.reason = String(e && e.message || e);
    return null;
  }
}

function load() {
  if (loaded) return mem;
  loaded = true;
  const s = ls();
  if (!s) {
    if (storage.available === null) { storage.available = false; storage.reason = 'localStorage unavailable'; }
    return mem;
  }
  try {
    const raw = s.getItem(STORE_KEY);
    storage.available = true;
    if (!raw) return mem;
    const p = JSON.parse(raw);
    if (!p || typeof p !== 'object' || p.v !== 1) return mem;     // a future/unknown shape is ignored, not migrated
    mem = {
      v: 1,
      best: (p.best && typeof p.best === 'object') ? p.best : {},
      hintDone: !!p.hintDone,
      finished: !!p.finished,
    };
  } catch (e) {
    // Corrupt JSON, a quota error on read in some embedders, a revoked permission mid-session.
    storage.available = false;
    storage.reason = String(e && e.message || e);
    mem = blank();
  }
  return mem;
}

function save() {
  const s = ls();
  if (!s) return false;
  try { s.setItem(STORE_KEY, JSON.stringify(mem)); storage.available = true; return true; }
  catch (e) {
    // Private browsing / quota exceeded. The in-memory mirror still holds this session.
    storage.available = false;
    storage.reason = String(e && e.message || e);
    return false;
  }
}

/** The whole record (a copy — callers must not mutate it). */
export function progress() { const p = load(); return { ...p, best: { ...p.best } }; }

/** `{score, stars}` for a level, or null if it has never been cleared. */
export function bestFor(id) {
  const b = load().best[id];
  return b && Number.isFinite(b.score) ? { score: b.score, stars: b.stars | 0 } : null;
}

export function totalStars() {
  const b = load().best;
  return LEVEL_ORDER.reduce((n, id) => n + ((b[id]?.stars | 0) || 0), 0);
}

/** How far the player has got: 0-based index of the furthest level they may open. */
export function furthestUnlocked() {
  const b = load().best;
  let i = 0;
  for (let k = 0; k < LEVEL_ORDER.length - 1; k++) { if (b[LEVEL_ORDER[k]]) i = k + 1; else break; }
  return i;
}

/**
 * Record an attempt. Keeps the BEST score and the BEST stars independently — a 3-star run
 * that scored less than a sloppier 1-star run should not lose the player their stars.
 * @returns {{score:number, stars:number, improved:boolean, saved:boolean}}
 */
export function recordResult(id, score, stars) {
  if (isFixture(id)) return { score, stars, improved: false, saved: false };
  const p = load();
  const prev = p.best[id];
  const best = {
    score: Math.max(prev?.score ?? 0, score | 0),
    stars: Math.max(prev?.stars ?? 0, stars | 0),
  };
  const improved = !prev || best.score > (prev.score ?? 0) || best.stars > (prev.stars ?? 0);
  p.best[id] = best;
  if (isLastLevel(id) && stars > 0) p.finished = true;
  const saved = save();
  return { ...best, improved, saved };
}

/**
 * THE PERSISTED INTENTION, AND IT IS NAMED AS ONE. The tutorial hint is a one-time thing:
 * after the player's first real draw it never shows again, on this device.
 *
 * This is deliberately NOT called `hintDone` any more. `state().hintDone` answers "is the
 * hint off the screen", measured off the DOM; this answers "has the player ever drawn the
 * band back". The two are different facts and the old shared name let a saved flag speak
 * for the screen — which is precisely how `hintDone:true` came to be reported while the
 * line was still rendered at opacity .92. The STORED key stays `hintDone` so an existing
 * v1 save keeps working; only the code-facing name changed.
 */
export function hintSeen() { return !!load().hintDone; }
export function markHintSeen() { const p = load(); if (p.hintDone) return false; p.hintDone = true; save(); return true; }

/** Has the player ever finished l3? Drives the finish panel's "again" wording. */
export function finished() { return !!load().finished; }

/**
 * Wipe the saved record. GRACEFUL: if storage cannot be written the in-memory record is
 * still cleared and the call still reports success for this session, because the player
 * pressed a button and something visible must happen.
 */
export function resetProgress() {
  mem = blank();
  loaded = true;
  const s = ls();
  let removed = false;
  try { if (s) { s.removeItem(STORE_KEY); removed = true; } }
  catch (e) { storage.available = false; storage.reason = String(e && e.message || e); }
  scoring.starsClamped = 0;
  return { ok: true, persisted: removed, storage: storage.available, reason: storage.reason };
}

/** Test seam: forget what we read so the next call re-reads storage. Never called by the game. */
export function __reload() { loaded = false; mem = blank(); return load(); }
