#!/usr/bin/env bash
#
# ifm-mark.sh — mark content "Do Not Use" so the Library stops showing it.
#
# This is the everyday cleanup tool. It is REVERSIBLE and touches nothing on Drive.
#
#   scripts/ifm-mark.sh --list                      what is currently marked
#   scripts/ifm-mark.sh IFM-044 IFM-045 IFM-053     mark these (shows them, asks first)
#   scripts/ifm-mark.sh --undo IFM-044              put one back
#   scripts/ifm-mark.sh --yes IFM-044 ...           skip the confirmation
#
# THE THREE STAGES, and why they are separate
#
#   1. MARK      here.                        Reversible. Nothing on Drive moves.
#                The asset leaves the Library on the next page load.
#   2. DEPLOY    scripts/ifm-deploy.sh.       Makes the change live for the team.
#   3. RETIRE    scripts/ifm-retire-assets.sh Moves the Drive file to _Trash.
#                Only ever acts on things already marked here. Still recoverable.
#
# You can stop after 1. Most cleanup should: hiding an asset costs nothing and can be
# undone in a second, whereas moving a file is a decision about someone else's work.
#
# WHY NOT THE CATALOGUE SHEET
#   The V1 prototype reads five local files and no sheet — verified, zero gviz calls in
#   index.html. The sheet overrides the HUB (content/index.html), not this. Marking there
#   would look right and do nothing.
#
# WHY IT WRITES TWICE
#   v1-catalogue.js is GENERATED by backfill.py. A mark recorded only there is reverted by
#   the next regeneration. enrichment.json is the override layer backfill.py merges AFTER
#   its rules, so the mark is written to both and survives.
set -euo pipefail

MODE="mark"; ASSUME_YES=0; IDS=()
for a in "$@"; do
  case "$a" in
    --list) MODE="list" ;;
    --undo) MODE="undo" ;;
    --yes|-y) ASSUME_YES=1 ;;
    --help|-h) sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    IFM-*) IDS+=("$a") ;;
    *) echo "unknown argument: $a  (try --help)" >&2; exit 2 ;;
  esac
done

ROOT=$(git -C "$(dirname "$0")" rev-parse --show-toplevel)
DIR="$ROOT/CLAUDE/content/v1-prototype"

/usr/bin/python3 - "$DIR" "$MODE" "$ASSUME_YES" "${IDS[@]+"${IDS[@]}"}" <<'PY'
import json, os, sys

DIR, MODE, ASSUME_YES = sys.argv[1], sys.argv[2], sys.argv[3] == '1'
IDS = sys.argv[4:]
CAT, ENR = os.path.join(DIR, 'v1-catalogue.js'), os.path.join(DIR, 'enrichment.json')
MARK = 'Do Not Use'

src = open(CAT, encoding='utf-8').read()
head = src[:src.index('[')]
rows = json.loads(src[src.index('['):src.rindex(']') + 1])
by = {r['id']: r for r in rows}

def marked():
    return [r for r in rows if (r.get('status') or '') == MARK]

if MODE == 'list':
    m = marked()
    print('\n  %d asset(s) marked "%s":\n' % (len(m), MARK))
    for r in m:
        print('    %-9s %s' % (r['id'], (r.get('title') or '')[:64]))
    if not m:
        print('    (none)')
    print('\n  Library now shows %d of %d catalogued.\n'
          % (len([r for r in rows if r.get('library') is not False
                  and (r.get('status') or '') != MARK]), len(rows)))
    sys.exit(0)

if not IDS:
    sys.exit('No asset ids given. Try --list, or pass ids like IFM-044 IFM-045.')

unknown = [i for i in IDS if i not in by]
if unknown:
    sys.exit('FATAL: not in the catalogue: %s' % ', '.join(unknown))

# Show exactly what is about to change, with the previous status, before touching anything.
verb = 'Un-marking' if MODE == 'undo' else 'Marking'
print('\n  %s %d asset(s):\n' % (verb, len(IDS)))
for i in IDS:
    r = by[i]
    print('    %-9s  status %-12s  %s' % (i, (r.get('status') or '-'), (r.get('title') or '')[:54]))

if MODE == 'undo':
    print('\n  They will return to the Library. Their previous status is not restored —')
    print('  they become "Raw" unless you set something else in the catalogue.')
else:
    print('\n  They leave the Library on the next page load. Nothing on Drive moves.')
    print('  Reverse any of it with:  scripts/ifm-mark.sh --undo <id>')

if not ASSUME_YES:
    if not sys.stdin.isatty():
        sys.exit('\nNo terminal to confirm on. Re-run with --yes if you meant this.')
    if input('\n  Proceed? [y/N] ').strip().lower() not in ('y', 'yes'):
        sys.exit('  Nothing changed.')

for i in IDS:
    by[i]['status'] = 'Raw' if MODE == 'undo' else MARK

with open(CAT, 'w', encoding='utf-8') as f:
    f.write(head); json.dump(rows, f, ensure_ascii=False, indent=1); f.write(';\n')

enr = json.load(open(ENR, encoding='utf-8'))
for i in IDS:
    if MODE == 'undo':
        if i in enr and isinstance(enr[i], dict):
            enr[i].pop('status', None)
            if not enr[i]:
                enr.pop(i)
    else:
        enr.setdefault(i, {})['status'] = MARK
with open(ENR, 'w', encoding='utf-8') as f:
    json.dump(enr, f, ensure_ascii=False, indent=1); f.write('\n')

lib = [r for r in rows if r.get('library') is not False and (r.get('status') or '') != MARK]
print('\n  Done. Library: %d of %d catalogued.' % (len(lib), len(rows)))
print('  Written to v1-catalogue.js and enrichment.json (so a regeneration keeps it).')
print('  Run scripts/ifm-deploy.sh to make it live.\n')
PY
